# .github/config.yml

blank_issues_enabled: true
contact_links:
  - name: 'Report a Bug'
    url: '/issues/new?template=bug_report.md'
    about: 'Use this template to report a bug in the application.'
  - name: 'Feature Request'
    url: '/issues/new?template=feature_request.md'
    about: 'Use this template to suggest a new feature or enhancement.'
  - name: 'Support Request'
    url: '/issues/new?template=support_request.md'
    about: 'Use this template for general support questions.'

# Issue templates
issue_templates:
  - name: 'Bug Report'
    description: 'Report a bug in the application.'
    body:
      - type: markdown
        attributes:
          value: 'Please fill out the following information to help address your issue.'
      - type: input
        id: title
        attributes:
          label: 'Issue Title'
          description: 'A short summary of the issue.'
          placeholder: 'Title of the bug'
      - type: textarea
        id: description
        attributes:
          label: 'Description'
          description: 'A detailed description of the issue.'
          placeholder: 'Describe the bug in detail...'
      - type: checkbox
        id: steps_to_reproduce
        attributes:
          label: 'Steps to Reproduce'
          description: 'List the steps to reproduce the issue.'
          options:
            - 'Step 1'
            - 'Step 2'
            - 'Step 3'
      - type: textarea
        id: expected_behavior
        attributes:
          label: 'Expected vs. Actual Behavior'
          description: 'What you expected to happen vs. what actually happened.'
          placeholder: 'Describe what you expected vs. what actually happened...'

  - name: 'Feature Request'
    description: 'Suggest a new feature or enhancement.'
    body:
      - type: markdown
        attributes:
          value: 'Please provide a detailed description of the feature you would like to see.'
      - type: input
        id: feature_title
        attributes:
          label: 'Feature Title'
          description: 'A short summary of the feature.'
          placeholder: 'Title of the feature'
      - type: textarea
        id: feature_description
        attributes:
          label: 'Feature Description'
          description: 'A detailed description of the feature.'
          placeholder: 'Describe the feature in detail...'

  - name: 'Support Request'
    description: 'Ask a question or request support.'
    body:
      - type: markdown
        attributes:
          value: 'Please provide details about your support request.'
      - type: textarea
        id: support_description
        attributes:
          label: 'Support Request Description'
          description: 'Describe your support request.'
          placeholder: 'What do you need help with?'
