name: Flatpak Build (Testing)

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with debug logging'
        type: boolean
        required: false
        default: false

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.5
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: -1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Setup Flatpak
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08 org.electronjs.Electron2.BaseApp//23.08

      - name: Add Flatpak manifest
        run: |
          cat > org.alichtman.deadbolt.yml << 'EOF'
          app-id: org.alichtman.deadbolt
          runtime: org.freedesktop.Platform
          runtime-version: '23.08'
          sdk: org.freedesktop.Sdk
          base: org.electronjs.Electron1.BaseApp
          base-version: '23.08'
          command: deadbolt
          finish-args:
            - --share=ipc
            - --socket=x10
            - --socket=wayland
            - --device=dri
            - --filesystem=home
            - --env=GDK_BACKEND=wayland,x10
            - --env=ELECTRON_OZONE_PLATFORM_HINT=auto
          modules:
            - name: deadbolt
              buildsystem: simple
              build-commands:
                - mkdir -p /app/deadbolt
                - cp -r * /app/deadbolt/
                - mkdir -p /app/bin
                - ln -s /app/deadbolt/deadbolt /app/bin/deadbolt
              sources:
                - type: dir
                  path: .
          EOF

      - name: Build Flatpak package
        run: |
          flatpak-builder --repo=repo --force-clean build-dir org.alichtman.deadbolt.yml
          flatpak build-bundle repo deadbolt.flatpak org.alichtman.deadbolt

      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-bundle
          path: deadbolt.flatpak

      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: deadbolt.flatpak
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
